export const SOURCES = [
    {
        key: 'vidzee',
        label: 'VidZee',
        proxyParam: 'vz',
        timeout: 15000,
        jitter: 400,
        retries: 3,
        sourcesTimeout: 5000,
    },
    {
        key: 'vidnest',
        label: 'VidNest',
        proxyParam: 'vn',
        timeout: 20000,
        jitter: 600,
        retries: 3,
    },
    {
        key: 'vidsrc',
        label: 'VidSrc',
        proxyParam: 'vs',
        timeout: 25000,
        jitter: 700,
        retries: 2,
    },
    {
        key: 'vidrock',
        label: 'VidRock',
        proxyParam: 'vr',
        timeout: 20000,
        jitter: 800,
        retries: 3,
    },
    {
        key: 'cinesu',
        label: 'CineSu',
        proxyParam: 'cs',
        timeout: 15000,
        jitter: 500,
        retries: 2,
    },
    {
        key: 'vixsrc',
        label: 'VixSrc',
        proxyParam: 'vx',
        timeout: 20000,
        jitter: 500,
        retries: 2,
    },
    {
        key: 'vidlink',
        label: 'VidLink',
        proxyParam: 'vl',
        timeout: 25000,
        jitter: 500,
        retries: 2,
    },
    {
        key: '02movie',
        label: '02Movie',
        proxyParam: 'zm',
        timeout: 20000,
        jitter: 600,
        retries: 2,
        skipProxy: true,
    },
    {
        key: 'meowtv',
        label: 'MeowTV',
        proxyParam: 'mt',
        timeout: 20000,
        jitter: 500,
        retries: 2,
    },
    {
        key: 'vaplayer',
        label: 'AirFlix',
        proxyParam: 'af',
        timeout: 20000,
        jitter: 600,
        retries: 2,
        skipProxy: true,
        disabled: true,
    },
    {
        key: 'icefy',
        label: 'Icefy',
        proxyParam: 'iy',
        timeout: 20000,
        jitter: 500,
        retries: 2,
    },
    {
        key: 'videasy',
        label: 'Videasy',
        proxyParam: 'vy',
        timeout: 20000,
        jitter: 900,
        retries: 3,
    },
];

export const SOURCE_MAP = Object.fromEntries(SOURCES.map(s => [s.key, s]));
export const ALLOWED_ORIGINS = ['*'];
export const HEALTH_PROBE_ID = '155';
export const CACHE_TTL = 5 * 60 * 1000;